var arr = [1, 2, "abc"];
var c = 2;
print(arr);
print(arr[0]);
print(arr.indexOf("abc"));
print(arr[2]);
print(arr[c]);
arr[3] = 5;
arr[4] = 5;
print(arr.indexOf(5));
print(arr[3]-1);
print(arr.length);
arr.push(7);
print(arr.length);
print(arr[5]);
print(arr);
print(arr.join("|"));
print(arr.join(''));
