var buffer1 = new ArrayBuffer();
var buffer2 = new ArrayBuffer(20);
print(buffer1.byteLength);
print(buffer2.byteLength);
var arr1 = new Int32Array(buffer1);
print(arr1.length);
var arr2 = new Int8Array(buffer2);
print(arr2.length);
var arr3 = new Int16Array(buffer2, 2);
print(arr3.length);
var arr4 = new Int32Array(buffer2, 4, 2);
print(arr4.length);
