#!/bin/bash

BIN_ID=./escargot.id
BIN_IR=./escargot.ir
BIN_JD=./escargot.jd
BIN_JR=./escargot.jr

#TC_FILE=TC.test
#TC_FILE=TC.sunspider
TC_FILE=TC.regression
ARGS=

TC=`cat $TC_FILE | xargs`

MASK=12
#MASK=1
#MASK=2
#MASK=4
#MASK=8

if ((($MASK & 1) != 0))
then
	echo "#### Interpreter Debug"
	for t in $TC; do
		echo "===>" $t
		$BIN_ID $ARGS $t
	done
fi

if ((($MASK & 2) != 0))
then
	echo "#### Interpreter Release"
	for t in $TC; do
		echo "===>" $t
		$BIN_IR $ARGS $t
	done
fi

if ((($MASK & 4) != 0))
then
	echo "#### JIT Debug"
	for t in $TC; do
		echo "===>" $t
		$BIN_JD $ARGS $t
	done
fi

if ((($MASK & 8) != 0))
then
	echo "#### JIT Release"
	for t in $TC; do
		echo "===>" $t
		$BIN_JR $ARGS $t
	done
fi

