#!/bin/bash

TC_FILE=test262.regression
ARGS=

TC=`cat $TC_FILE | xargs`

make x64.interpreter.release -j8
for t in $TC; do
    if [[ $t == \#* ]]; then
        continue
    fi
    echo $t
    make run-test262 OPT=$t > out/test_262
    cat out/test_262 | grep "\- Failed"
done

make x64.interpreter.debug -j8
for t in $TC; do
    if [[ $t == \#* ]]; then
        continue
    fi
    echo $t
    make run-test262 OPT=$t > out/test_262
    cat out/test_262 | grep "\- Failed"
done

exit 0;
