// THIS IS AUTO-GENERATED BY create.rb
var SimplePayload = [
    {name: "towers.c"},
    {name: "container.cpp"},
    {name: "dry.c"},
    {name: "n-body.c"},
    {name: "quicksort.c"},
    {name: "gcc-loops.cpp"},
    {name: "hash-map"},
    {name: "float-mm.c"},
    {name: "bigfib.cpp"},
];
