// THIS IS AUTO-GENERATED BY create.rb
var SunSpiderPayload = [
    {name: "3d-cube"}, 
    {name: "3d-raytrace"},
    {name: "base64"}, 
    {name: "crypto-aes"},
    {name: "crypto-md5"}, 
    {name: "crypto-sha1"},
    {name: "date-format-tofte"},
    {name: "date-format-xparb"}, 
    {name: "n-body"}, 
    {name: "regex-dna"}, 
    {name: "tagcloud"},
];
